### ISSUE TITLE
Not working on Macbook15,1 linux-6.14.7

### ISSUE THREAD

**Issue by Uture** [roadrunner2/macbook12-spi-driver#74]
I can build and install the driver (branch: mbp15) using dkms. The module shows up in lsmod but it doesn't seem to bind to the SPI bus (it's not listed in /sys/bus/spi/drivers). The touchbar and trackpad aren't working.

dmesg shows no errors at all relating to the installed module.

Help appreciated!

**Comment by pedroresende** [comment]
any news on this ?

**Comment by pedroresende** [comment]
@Uture try using my repo https://github.com/pedroresende/macbook12-spi-driver it's working with 6.14

**Comment by anton-bregolas** [comment]
@pedroresende Thanks Pedro! Tried a few forks and yours worked perfectly (6.14.0-34)

**Comment by hirscherich** [comment]
@pedroresende what can i do w/t my macbook A1534 8.1 ? Fedora 43 works perfectly but no keyboard runs ? Try a lot of drivers, wirhout success.

**Comment by hirscherich** [comment]
Looking for a driver for Fedora W43, Chatgpr tells me, Kernel 6.17 is too new. Is there any help?

**Comment by 0x7061** [comment]
@pedroresende Your fork works for up to 6.14, so Ubuntu 24.04 should be safe? Thanks.

**Comment by walterklomp** [comment]
I can't build it on usr/src/linux-headers-6.8.0-101-generic - wha gives ?
root@walter-MacBookPro:~/macbook12-spi-driver# dkms install -m applespi -v 0.1

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=6.8.0-101-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for applespi: 0.1 not found
Error! Bad return status for module build on kernel: 6.8.0-101-generic (x86_64)
Consult /var/lib/dkms/applespi/0.1/build/make.log for more information.
root@walter-MacBookPro:~/macbook12-spi-driver# cat /var/lib/dkms/applespi/0.1/build/make.log
DKMS make.log for applespi-0.1 for kernel 6.8.0-101-generic (x86_64)
Rab 04 Mar 2026 10:40:08  WIB
make -C /lib/modules/6.8.0-101-generic/build M=/var/lib/dkms/applespi/0.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-101-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04.2) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04.3) 12.3.0
  CC [M]  /var/lib/dkms/applespi/0.1/build/applespi.o
/var/lib/dkms/applespi/0.1/build/applespi.c: In function ‘applespi_setup_read_txfrs’:
/var/lib/dkms/applespi/0.1/build/applespi.c:579:13: error: ‘struct spi_transfer’ has no member named ‘delay_usecs’
  579 |         dl_t->delay_usecs = applespi->spi_settings.spi_cs_delay;
      |             ^~
/var/lib/dkms/applespi/0.1/build/applespi.c: In function ‘applespi_setup_write_txfrs’:
/var/lib/dkms/applespi/0.1/build/applespi.c:600:13: error: ‘struct spi_transfer’ has no member named ‘delay_usecs’
  600 |         dl_t->delay_usecs = applespi->spi_settings.spi_cs_delay;
      |             ^~
/var/lib/dkms/applespi/0.1/build/applespi.c:604:13: error: ‘struct spi_transfer’ has no member named ‘delay_usecs’
  604 |         wr_t->delay_usecs = SPI_RW_CHG_DLY;
      |             ^~
/var/lib/dkms/applespi/0.1/build/applespi.c: At top level:
/var/lib/dkms/applespi/0.1/build/applespi.c:1840:27: error: initialization of ‘void (*)(struct spi_device *)’ from incompatible pointer type ‘int (*)(struct spi_device *)’ [-Werror=incompatible-pointer-types]
 1840 |         .remove         = applespi_remove,
      |                           ^~~~~~~~~~~~~~~
/var/lib/dkms/applespi/0.1/build/applespi.c:1840:27: note: (near initialization for ‘applespi_driver.remove’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/applespi/0.1/build/applespi.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-101-generic/Makefile:1936: /var/lib/dkms/applespi/0.1/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-101-generic'
make: *** [Makefile:11: all] Error 2
