### ISSUE TITLE
Won't compile on kernel 4.15.0

### ISSUE THREAD

**Issue by double16** [roadrunner2/macbook12-spi-driver#13]
The hid_report struct has changed so this won't compile on 4.15.0.

DKMS make.log for applespi-0.1 for kernel 4.15.0-36-generic (x86_64)
Mon Oct  8 07:19:46 CDT 2018
make -C /lib/modules/4.15.0-36-generic/build M=/var/lib/dkms/applespi/0.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-36-generic'
  CC [M]  /var/lib/dkms/applespi/0.1/build/applespi.o
  CC [M]  /var/lib/dkms/applespi/0.1/build/appletb.o
/var/lib/dkms/applespi/0.1/build/appletb.c: In function ‘appletb_find_hid_field’:
/var/lib/dkms/applespi/0.1/build/appletb.c:980:14: error: ‘struct hid_report’ has no member named ‘application’
    if (report->application != application)
              ^~
scripts/Makefile.build:339: recipe for target '/var/lib/dkms/applespi/0.1/build/appletb.o' failed
make[2]: *** [/var/lib/dkms/applespi/0.1/build/appletb.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1551: recipe for target '_module_/var/lib/dkms/applespi/0.1/build' failed
make[1]: *** [_module_/var/lib/dkms/applespi/0.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-36-generic'
Makefile:12: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by duncanam** [comment]
+1 for a mid 2017 Macbook Pro with touchbar running kernel 4.15.0. Cannot compile.

**Comment by roadrunner2** [comment]
Apologies for screwup. Fixed now.
