### ISSUE TITLE
Doesn´t work on kernel 6.14.0-28-generic (Ubuntu 24.04.3 LTS)

### ISSUE THREAD

**Issue by pedroresende** [roadrunner2/macbook12-spi-driver#75]
DKMS make.log for applespi-0.1 for kernel 6.14.0-28-generic (x86_64)
Tue Aug 26 03:41:10 PM WEST 2025
make -C /lib/modules/6.14.0-28-generic/build M=/var/lib/dkms/applespi/0.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.14.0-28-generic'
make[2]: Entering directory '/var/lib/dkms/applespi/0.1/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  apple-ibridge.o
  CC [M]  apple-ib-tb.o
  CC [M]  apple-ib-als.o
apple-ib-tb.c: In function ‘appletb_fill_report_info’:
apple-ib-tb.c:949:9: warning: enumeration value ‘HID_REPORT_TYPES’ not handled in switch [-Wswitch]
  949 |         switch (field->report->type) {
      |         ^~~~~~
apple-ibridge.c:192:6: warning: no previous prototype for ‘appleib_detach_and_free_hid_driver’ [-Wmissing-prototypes]
  192 | void appleib_detach_and_free_hid_driver(struct appleib_device *ib_dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apple-ibridge.c:752:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Werror=incompatible-pointer-types]
  752 |         .report_fixup = appleib_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~
apple-ibridge.c:752:25: note: (near initialization for ‘appleib_hid_driver.report_fixup’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-6.14.0-28-generic/scripts/Makefile.build:207: apple-ibridge.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-headers-6.14.0-28-generic/Makefile:2001: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.14.0-28-generic/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/applespi/0.1/build'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.14.0-28-generic'
make: *** [Makefile:30: all] Error 2

**Comment by 0x7061** [comment]
Bump
